services:
  mysql:
    image: mysql:8.0
    container_name: ticket-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ticketdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ticket-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ticket-app
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ticketdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure

volumes:
  mysql_data:
